### PR TITLE
Testing

### PR DESCRIPTION
**Pull request by ericgaspar**
- Upgrade tp 2.4.0

### CODE REVIEW

**Comment by ericgaspar** [comment]
!bullseyetestme

**Comment by ericgaspar** [comment]
!testme

**Comment by Salamandar** [comment]
Thanks @ericgaspar  :)

**Comment by Salamandar** [comment]
| :exclamation:  Don't merge it !    |
|-----------------------------------------|

I just tested it, and the `<domain>/wetty/ssh/admin` does not work anymore (it allows to connect as another user than the one connected to the SSO).
That's an important issue.

**Comment by yalh76** [comment]
!testme

**Pull request merged**
