### PR TITLE
Local build, to be sure of which version we use

### PR DESCRIPTION
**Pull request by Salamandar**

### CODE REVIEW

**Comment by Salamandar** [comment]
!testme

**Comment by alexAubin** [comment]
Hmmm getting 502 except for private install ... wondering if that's some bug in the new CI ...

**Comment by alexAubin** [comment]
!testme let's retry it just in case it magically goes away idk

**Comment by Salamandar** [comment]
Yeah, I tested locally and wetty just needs some time to be up and accessible. In the meantime nginx does not find the upstream for the proxy.

**Comment by alexAubin** [comment]
@Salamandar : are you aware of the `--line_match` arg in `ynh_systemd_action` ? That's what used to detect that a service actually finished starting before continuing with the script ... It's meant to match a specific string in the service's systemd journal, or a file log

c.f. for example https://github.com/YunoHost-Apps/wekan_ynh/blob/master/scripts/install#L156

**Comment by yalh76** [comment]
!testme

**Comment by Salamandar** [comment]
!testme

**Comment by yalh76** [comment]
oupsi ^^

**Comment by Salamandar** [comment]
!testme

I just force-pushed to the branch and IDK if the yunorunner references the branch or the commit.

**Comment by yalh76** [comment]
> 
> 
> !testme
> 
> I just force-pushed to the branch and IDK if the yunorunner references the branch or the commit.

It took the last commit when it's launched

**Comment by yalh76** [comment]
Ready for level 7

**Review by ericgaspar — APPROVED** [review]

**Comment by Salamandar** [comment]
@yalh76 hmmm there is a weird thing in the logs.
```
38759 INFO [##############+.....] > Starting a systemd service...
340990 WARNING Please wait, the service wetty is starting..........................................................................................................................................................................................................................................................................................................
341013 WARNING The service wetty didn't fully executed the action start before the timeout.
341033 WARNING Please find here an extract of the end of the log of the service wetty:
341113 WARNING May 19 00:31:36 systemd[5062]: wetty.service: Failed at step STDOUT spawning /opt/node_n/n/versions/node/14/bin/node: No such file or directory
341113 WARNING May 19 00:31:36 systemd[1]: Started Wetty Web Terminal.
341113 WARNING May 19 00:31:36 systemd[1]: wetty.service: Main process exited, code=exited, status=209/STDOUT
341114 WARNING May 19 00:31:36 systemd[1]: wetty.service: Failed with result 'exit-code'.
341114 WARNING May 19 00:31:38 systemd[1]: wetty.service: Service RestartSec=2s expired, scheduling restart.
341114 WARNING May 19 00:31:38 systemd[1]: wetty.service: Scheduled restart job, restart counter is at 134.
341115 WARNING May 19 00:31:38 systemd[1]: Stopped Wetty Web Terminal.
341115 WARNING May 19 00:31:38 systemd[1]: Started Wetty Web Terminal.
341115 WARNING May 19 00:31:38 systemd[5067]: wetty.service: Failed to set up standard output: No such file or directory
341116 WARNING May 19 00:31:38 systemd[5067]: wetty.service: Failed at step STDOUT spawning /opt/node_n/n/versions/node/14/bin/node: No such file or directory
341116 WARNING May 19 00:31:38 systemd[1]: wetty.service: Main process exited, code=exited, status=209/STDOUT
341116 WARNING May 19 00:31:38 systemd[1]: wetty.service: Failed with result 'exit-code'.
341117 WARNING May 19 00:31:40 systemd[1]: wetty.service: Service RestartSec=2s expired, scheduling restart.
341117 WARNING May 19 00:31:40 systemd[1]: wetty.service: Scheduled restart job, restart counter is at 135.
341118 WARNING May 19 00:31:40 systemd[1]: Stopped Wetty Web Terminal.
341118 WARNING May 19 00:31:40 systemd[5072]: wetty.service: Failed to set up standard output: No such file or directory
341118 WARNING May 19 00:31:40 systemd[5072]: wetty.service: Failed at step STDOUT spawning /opt/node_n/n/versions/node/14/bin/node: No such file or directory
341119 WARNING May 19 00:31:40 systemd[1]: Started Wetty Web Terminal.
341119 WARNING May 19 00:31:40 systemd[1]: wetty.service: Main process exited, code=exited, status=209/STDOUT
341119 WARNING May 19 00:31:40 systemd[1]: wetty.service: Failed with result 'exit-code'.
341278 INFO [###############++...] > Restoring the logrotate configuration...
```

**Comment by Salamandar** [comment]
!testme

the /var/log/$app directory was created after the systemctl start. That should be fixed now.

**Comment by Salamandar** [comment]
!testme

**Pull request merged**
